# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f5ad7ad3c0f8a5e933f751335cf67105c7e68e23d11e55b4d9de50e1f10362712b27de3ab0ee8ce0bcb048df7fc3307aea5e755b0e15933e6dda704ff5f05f35

test:
  secret_key_base: c8abea0ebb7c82f487bbe66907528f6ade3adc4bb2e7b42f334df4b2ab0beac7c5f6185a43488766522a994a984c9aca9c057c7c2759feaa6276a43af6068628

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
